- BMSAPI.postman_collection.json
Added tests for the ff:
1. GET /study/{cropname}/{studyId}/instances
2. GET /study/{cropName}/{studyId}/sampled
> Add tests for study services

- BMS_Environment2.postman_environment.json
- BMS_Environment3.postman_environment.json
- BMS_Environment4.postman_environment.json
- BMS_Environment5.postman_environment.json
- BMS_Environment6.postman_environment.json
updated value of study_sampleId per environment instance
> updated value of study_sampleId per environment instance

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
Added tests for:
- POST /{crop}/brapi/v1/search/germplasm
- GET /{crop}/brapi/v1/search/germplasm/{searchResultsDbid}
> Brapi search service updated

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
- BMS_Environment2.postman_environment.json
- BMS_Environment3.postman_environment.json
- BMS_Environment4.postman_environment.json
- BMS_Environment5.postman_environment.json
- BMS_Environment6.postman_environment.json
Added tests for the ff:
GET /crops/{crop}/studies/{studyId}/datasets/{datasetId}/derived-variables/{variableId}/formula-variables/dataset-map
GET /crops/{crop}/studies/{studyId}/datasets/{datasetId}/derived-variables/{variableId}/formula-variables/missing
HEAD /crops/{crop}/studies/{studyId}/derived-variables
> Derived variable services

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
1. Added tests for the ff:
- PATCH /{crop}​/brapi​/v2​/observationunits​/{observationUnitDbId}
- POST ​/{crop}​/brapi​/v2​/search​/observationunits
- GET ​/{crop}​/brapi​/v2​/search​/observationunits​/{searchResultsDbid}
- PUT ​/{crop}​/brapi​/v1​/studies​/{studyDbId}​/observations
- GET ​/{crop}​/brapi​/v1​/germplasm
- GET ​/{crop}/brapi​/v1​/calls
2. Added environment variables for placeholders of searchResultDbIds returned by POST ​/{crop}​/brapi​/v2​/search​/observationunits
3. Added environment variables for PUT ​/{crop}​/brapi​/v1​/studies​/{studyDbId}​/observations tests
Tasks | /
-- | --
Followed basic standards |  ✅ 
Ensured that the List of API Services and Calls spreadsheet is updated | ✅  
Ensured that all test data created and used in …
> Continue brapi call tests

- BMS_Environment.postman_environment.json
Tasks |  ✅ / ❌ 
Followed basic standards | ✅ |
Ensured that the List of API Services and Calls (old) page is updated |  **nothing to change** |  
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page |  **nothing to change** |
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  
Ensured that Testlink is updated | ✅ |
Ensured that the entire test suite is passing in master using PostmanCollections-CIRun and PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  
Deleted branch |  
> remove port number

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
**List of Changes**
1. Fix failing tests after adding new testdata
2. Add tests for experimental-design-type-resource
3. Add tests for inventory-unit-resource
4. Add tests for study-instance-resource
5. Add tests for experimental-design-resource
Tasks | /
-- | --
Followed basic standards | ✅   
Ensured that the List of API Services and Calls  spreadsheet is updated |  ✅ 
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page | ✅  
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  
Ensured that Testlink is updated | ✅   
Ensured that the entire test suite is …
> New branch api update

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
Tasks | /
-- | --
Followed basic standards |  ✅ 
Ensured that the List of API Services spreadsheet is updated |  ✅ 
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page |   ✅ 
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |   ✅ 
Ensured that Testlink is updated |  ✅ 
Ensured that the entire test suite is passing in master using PostmanCollections-CIRun and PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  
Deleted branch |  
Added tests on the following calls:
PATCH ​/crops​/{cropName}​/lot-lists
GET …
> added tests for lot-resource related calls

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
Tasks | /
-- | --
Followed basic standards |  ✅ 
Ensured that the List of API Services spreadsheet is updated |  ✅ 
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page |  ✅ 
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  ✅ 
Ensured that Testlink is updated |  ✅ 
Ensured that the entire test suite is passing in master using PostmanCollections-CIRun and PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  
Deleted branch |  
Changes:
* Fix failing tests and update environment file
> fix failing test in inventory service

- BMSAPI.postman_collection.json
- BRAPI.postman_collection.json
1. Fixed failing tests on brapi (updated assertion on total counts)
2. Fixed failing tests on bmsapi (updated assertion index and added query parameters for study instance calls)
Tasks | /
-- | --
Followed basic standards | ✅   
Ensured that the List of API Services spreadsheet is updated | **no necessary change**
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page |  **no necessary change**
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  ✅   
Ensured that Testlink is updated | **no necessary change** 
Ensured that the entire test suite …
> Fix study failing tests

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
Added Manage Observations folder with tests for:
1. PUT /crops/{cropName}/programs​/{programUUID}​/studies/{studyId}/datasets/{datasetId}/observationUnits/observations
2. POST /crops/{cropName}/programs​/{programUUID}​/studies/{studyId}/datasets/{datasetId}/observation-units/drafts/rejection
3. POST /crops/{cropName}/programs​/{programUUID}​/studies/{studyId}/datasets/{datasetId}/observation-units/drafts/acceptance
4. DELETE ​/crops​/{crop}​/programs​/{programUUID}​/studies​/{studyId}​/datasets​/{datasetId}​/observationUnits​/{observationUnitId}​/observations​/{observationId}
Tasks | /
-- | --
Followed basic standards | ✅   
Ensured that the List of API Services spreadsheet is updated |  ✅ 
Ensured that all test data created and used in the tests …
> Dataset resource new

- BMSAPI.postman_collection.json
1. Added new tests and workflow for the ff:
- POST ​/crops​/{crop}​/programs​/{programUUID}​/studies​/{studyId}​/datasets​/{datasetId}​/observation-units​/observations​ filter​/count
- POST ​/crops​/{crop}​/programs​/{programUUID}​/studies​/{studyId}​/datasets​/{datasetId}​/observation-units​/observations​ filter​/count
- POST ​/crops​/{crop}​/programs​/{programUUID}​/studies​/{studyId}​/datasets​/{datasetId}​/observation-units​/drafts​/filter​/acceptance
- POST ​/crops​/{crop}​/programs​/{programUUID}​/studies​/{studyId}​/datasets​/{datasetId}​/observation-units​/drafts​/set-as-missing
2. Added tests for invalid crop and program for the ff:
- GET ​/crops​/{crop}​/programs​/{programUUID}​/studies​/{studyId}​/datasets​/{datasetId}​/instances
- GET …
> Dataset resource - Manage Observations update

- BMSAPI.postman_collection.json
**Changes:**
removed sortedPageRequest from body and moved to query parameters for all tests of POST ​/crops​/{cropname}​/programs​/{programUUID}​/studies​/{studyId}​/datasets​/{datasetId}​/observationUnits​/table
**Note:** This is caused by changes in IBP-3899
Tasks | /
-- | --
Ensured that the List of API Services spreadsheet is updated | **NA** 
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs | http://35.185.223.121/job/PostmanCollections-CIRun/509/console 
Ensured that TM4J test …
> Fix failing tests 20200916

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
**Changes:**
Updated the value (server URL) in the BMSUrl variable in environments file
Tasks | /
-- | --
Ensured that the List of API Services spreadsheet is updated | **NA** 
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs | http://35.185.223.121/job/PostmanCollections-CIRun/509/console 
Ensured that TM4J test cases are updated | **NA**  
**Post-merging** |  
Ensured that the entire test suite is passing in master using PostmanCollections-CIRun and PostmanCollections-PerfTests (if …
> Update server url

- BMSAPI.postman_collection.json
- BRAPI.postman_collection.json
1. updated assertion of validation message when passed invalid loc abbrto POST /crops/{cropName}/lot-lists
2. added sortBy query parameter to GET ​/{crop}​/brapi​/v1​/trials that tests sorting in asc and desc order
Tasks | /
-- | --
Ensured that the List of API Services spreadsheet is updated | **NA** 
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs | http://35.185.223.121/job/PostmanCollections-CIRun/583/console …
> Fix failing tests 20201028

- BMS_Environment.postman_environment.json
- BRAPI.postman_collection.json
1. Added tests to cover the ff. scenarios for GET ​/{crop}​/brapi​/v2​/trials
- Verify response code and body when entered crop name only
- Verify response code and body when filtered by commonCropName
- Verify response code and body when filtered by contactDbId
- Verify response code and body when filtered by programDbId
- Verify response code and body when filtered by locationDbId
- Verify response code and body when filtered by studyDbId
- Verify response code and body when filtered by trialDbId
- Verify response code and body when filtered by trialName
- Verify response code and body when filtered by trialPUI
- Verify response code and body when filtered by searchDateRangeEnd
- Verify response code and body when filtered by searchDateRangeStart
- Verify response …
> Get trial v2

- BRAPI.postman_collection.json
Add tests for GET ​/{crop}​/brapi​/v2​/studies:
1. Verify response code and body when entered crop only
2. Verify response code and body when filtered by studyTypeDbId
3. Verify response code and body when filtered by commonCropName
4. Verify response code and body when filtered by programDbId
5. Verify response code and body when filtered by locationDbId
6. Verify response code and body when filtered by seasonDbId
7. Verify response code and body when filtered by trialDbId
8. Verify response code and body when filtered by trialName
9. Verify response code and body when filtered by studyPUI
10. Verify response code and body when filtered by germplasmDbId
11. Verify response code and body when filtered by observationVariableDbId
12. Verify response code and body when …
> Brapi v2 studies

- BMSAPI.postman_collection.json
Added tests for the ff. calls:
- PATCH ​/crops​/{cropName}​/germplasm
- GET ​/crops​/{cropName}​/germplasm​/attributes
- GET ​/crops​/{cropName}​/germplasm​/attributes​/search
- GET ​/crops​/{cropName}​/germplasm​/name-types
- GET ​/crops​/{cropName}​/germplasm​/name-types​/search
- POST ​/crops​/{cropName}​/germplasm​/search
- GET ​/crops​/{cropName}​/germplasm​/{gid}
Tasks | /
-- | --
Followed basic standards | ✅   
Ensured that the List of API Services spreadsheet is updated | ✅  
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are …
> Germplasm resource 2

- BRAPI.postman_collection.json
List of changes:
1. removed assertion of observations[ ] from affected calls
2. updated assertions on brapi get program calls
3. updated assertions on v2/seedlots
(additional changes for the previous PR)
> removed assertion of observations[ ] from affected calls and updated assertions on brapi get program calls

- BMSAPI.postman_collection.json
Affected bmsapi calls:
GET /crops​/{cropName}​/location-types
GET /crops​/{cropName}​/locations​/{locationId}
GET /crops​/{cropname}​/locations
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  ✅ http://ci.leafnode.io/job/PostmanCollections-CIRun/687/console
Ensured that TM4J test cases are updated | ✅  New test cases are also added
Created backup of the current test data | ✅ …
> added tests for location related calls

- BMSAPI.postman_collection.json
Affected bmsapi calls:
- GET /users/filter
- GET /users
- GET /crops/{cropname}/study-types/visible
- GET /crops​/{crop}​/programs​/{programUUID}​/samples
- POST ​/crops​/{crop}​/programs​/{programUUID}​/sample-list-folders
- GET ​/crops​/{crop}​/sample-lists​/search 
- GET ​/crops​/{crop}​/sample-lists​/tree
- GET ​/crops​/{crop}​/sample-lists​/{listId}​/download
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to …
> added tests for bmsapi calls

- BMSAPI.postman_collection.json
POST ​/crops​/{cropName}​/transactions​/confirmed-deposits​/generation
- added new LOTUUID
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  ✅ http://ci.leafnode.io/job/PostmanCollections-CIRun/718/console
Ensured that TM4J test cases are updated | ✅
Created backup of the current test data | **N/A**
**Post-merging** |  
Ensured that the entire test suite is passing in master …
> fix-failing-lot-tests

- BMSAPI.postman_collection.json
Affected bmsapi calls:
* GET /crops/{cropName}/germplasm/{gid}/lists
* POST ​/crops​/{cropName}​/germplasm​/{gid}​/attributes
* GET ​/crops​/{cropName}​/germplasm​/{gid}​/attributes
* GET ​/crops​/{cropName}​/germplasm​/attributes
* PATCH ​/crops​/{cropName}​/germplasm​/{gid}​/attributes​/{attributeId}
* DELETE ​/crops​/{cropName}​/germplasm​/{gid}​/attributes​/{attributeId}
* GET ​/crops​/{cropName}​/germplasm​/{gid}​/samples
* GET ​/crops​/{cropName}​/germplasm​/{gid}​/progenitor-details
* GET ​/crops​/{cropName}​/germplasm​/{gid}​/studies
* GET ​/crops​/{cropName}​/germplasm​/{gid} --- updated
Tasks | /
-- | --
Ensured that all test data created …
> added tests for IBP-4428 and IBP-4415

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
Affected bmsapi calls:
-- POST ​/crops​/{cropName}​/germplasm​/{gid}​/names
-- PATCH ​/crops​/{cropName}​/germplasm​/{gid}​/names​/{nameId}
-- DELETE ​/crops​/{cropName}​/germplasm​/{gid}​/names​/{nameId}
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  ✅ http://ci.leafnode.io/job/PostmanCollections-CIRun/741/console
Ensured that TM4J test cases are updated | ✅
Created backup of …
> Germplasm name resource

- BMSAPI.postman_collection.json
1. Add tests for PATCH ​/crops​/{cropName}​/germplasm​/{gid}​/basic-details
2. Update db backup
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  ✅ http://ci.leafnode.io/job/PostmanCollections-CIRun/763/console
Ensured that TM4J test cases are updated | ✅
Created backup of the current test data | ✅
**Post-merging** |   …
> Ibp 4522 patch germplasm basic details

- BRAPI.postman_collection.json
Added tests for the ff. scenarios for POST v2/trial
1. Verify response code and body entered complete set of inputs
2. Verify creation of multiple trials
3. Verify response code and body entered required inputs only
4. Verify response code and body when entered details that exceed max length of trialName
5. Verify response code and body when entered details that exceed max length of trialDescription
6. Verify response code and body when entered characters equal max length of field
7. Verify response code and body when entered details but with no trialName
8. Verify response code and body when entered details but with no trialDescription
9. Verify response code and body when entered details but with no startDate
10. Verify response code and body when entered details …
> Brapi post trial

- BRAPI.postman_collection.json
Added tests for the ff:
- Verify response code and body entered complete set of inputs
- Verify response code and body entered multiple germplasm entries
- Verify response code and body when entered required details only
- Verify response code and body when defaultDisplayName is not specified
- Verify response code and body when aquisitionDate is not specified
- Verify response code and body when countryOfOriginCode is not specified
- Verify response code and body when entered invalid codes
- Verify response code and body entered accession number greater than max length
- Verify response code and body entered attribute in additionalInfo greater than max length
- Verify response code and body entered commonCropName greater than max length
- Verify response code and …
> Post brapi germplasm

- BMS_Environment.postman_environment.json
> updated windows server URL

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
Added tests for POST ​/crops​/{cropname}​/variables​/analysis:
1. Verify response when created variable with analysis type and numeric trait variableId
2. Verify response when created variable with analysis summary type and categorical trait variableId
3. Verify response when created analysis variable which combination of property, scale and method already exists in another analysis variable
4. Verify response when created analysis variable which combination of property, scale and method already exists in another non-analysis variable
5. Verify response when created analysis variable analysis names that are not unique within the list
6. Verify response when created analysis variable without analysis name
7. Verify response when created analysis variable without …
> Ibp 5480 post variable analysis

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
- BRAPI.postman_collection.json
1. Add tests related to POST /lists
2. Fix tests related to GET ​/{crop}​/brapi​/v2​/serverinfo and GET ​/brapi​/v2​/serverinfo
Tasks | /
-- | --
Ensured that the List of API Services spreadsheet is updated | NA
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page | NA
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  ✅  http://ci.leafnode.io/job/PostmanCollections-CIRun/1203/console
Ensured that TM4J test cases are updated |  **NA**
Created backup of the current test data | N/A
Ensured that the entire test …
> added tests for POST /lists

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
1. Fix failing tests affected by the adjustment made for the character limit for name and attribute values
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |✅   https://ci.leafnode.io/job/PostmanCollections-CIRun/1239/console
Ensured that TM4J test cases are updated |  N/A
Created backup of the current test data | N/A
Ensured that the entire test suite is passing in …
> fix failing tests 042522

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
- BrAPI_Schema_Validators.postman_collection.json
Fix failing tests in the following:
GET ​/{crop}​/brapi​/v1​/studies​/{studyDbId}​/observationvariables
GET ​/{crop}​/brapi​/v2​/search​/variables​/{searchResultsDbId}
GET ​/{crop}​/brapi​/v1​/variables
GET ​/{crop}​/brapi​/v2​/variables
POST ​/{crop}​/brapi​/v2​/trials
Tasks | /
-- | --
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page | ✅
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |✅  https://ci.leafnode.io/job/PostmanCollections-CIRun/1255/console …
> fix failing tests

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
1. Fixed failing tests 
2. Applied changes for IBP-5660
3. Created new backup file
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |✅   https://ci.leafnode.io/job/PostmanCollections-CIRun/1265/console
Ensured that TM4J test cases are updated |  N/A
Created backup of the current test data | ✅ …
> Fix failing tests 050622

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
- BrAPI_Schema_Validators.postman_collection.json
Fix failing tests in the following:
GET ​/{crop}​/brapi​/v2​/search​/observationunits​/{searchResultsDbid}
POST ​/{crop}​/brapi​/v2​/observationunits
POST ​/{crop}​/brapi​/v2​/observations
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |✅  https://ci.leafnode.io/job/PostmanCollections-CIRun/1300/console
Ensured that TM4J test cases are updated |  N/A
Created backup of the current test …
> Fix failing test 051922

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
- BrAPI_Schema_Validators.postman_collection.json
Updated numeric value to decimal in POST ​/{crop}​/brapi​/v2​/observations
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |✅  https://ci.leafnode.io/job/PostmanCollections-CIRun/1305/console
Ensured that TM4J test cases are updated |  ✅  
Created backup of the current test data | N/A …
> Ibp 5642 accept decimal value

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
- BrAPI_Schema_Validators.postman_collection.json
* Fixed failing tests in lot and transaction resources in BMSAPI collection
Tasks | /
-- | --
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |✅  https://ci.leafnode.io/job/PostmanCollections-CIRun/1316/consoleFull
Ensured that TM4J test cases are updated |  N/A
Created backup of the current test data | N/A …
> Fix failing test 052422

- BMSAPI.postman_collection.json
- BMS_Environment.postman_environment.json
1. added tests for PUT v2/observations
2. fix failing tests for variable-resource-brapi
3. temporarily remove failing tests in GET v2/search/variable because of pending issue reported in IBP-6079
4. fix failing tests on dataset-resource
5. remove germplasmOrigin from POST ​/{crop}​/brapi​/v2​/germplasm tests
6. fix GET v2/observation tests
7. updated db backup
Tasks | ✅ / ❌ 
-- | --
Followed basic standards |  
Ensured that the List of API Services spreadsheet is updated | ✅  
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page | **N/A**
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to …
> Fix failing tests v22 3

- BMSAPI.postman_collection.json
1. Fixed failing tests in BMSAPI
2. Fixed failing tests in BRAPI
Tasks | ✅ / ❌ 
-- | --
Followed basic standards |  
Ensured that the List of API Services spreadsheet is updated | **N/A**   
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page | **N/A**
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs |  ✅https://ci.leafnode.io/job/PostmanCollections-CIRun/2054/console
Ensured that Zephyr Scale test cases are updated | **N/A**
Created backup of the current test data | ✅   …
> Fix failing tests v24.3 sprint

- BMSAPI.postman_collection.json
- BrAPI_Schema_Validators.postman_collection.json
1. Update assertions of ontologyDbIds
2. Update assertions of "null" to null
3. Update assertion of means to rounded-off value in phenotype-resource-brapi
4. Update index used in attribute-value-resource-brapi
5. Update AttributeSchema_V2 in schema validation
6. Update index in tests that asserts specific ontology variable
Tasks | ✅ / ❌ 
-- | --
Followed basic standards |  
Ensured that the List of API Services spreadsheet is updated | ✅
Ensured that all test data created and used in the tests are added in the Setting up Initial Data (Data Seeding) page | **N/A**
Ensured that the entire test suite is passing in branch using PostmanCollections-CIRun or PostmanCollections-PerfTests (if changes are related to performance test) jenkins jobs | …
> Fix failing tests v27
